stages:
  data_ingestion:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
      - INCLUDE_TOP
      - WEIGHTS
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - AUGMENTATION
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/kidneyDiseaseClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/kidneyDiseaseClassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json
